// The medicine guide: general, patient-leaflet-level information about
// medicines commonly prescribed at Tulasi Health Care. It's fixed content,
// served as-is and never generated by the model, so it can't hallucinate a
// dose or an interaction.
//
// BEFORE LAUNCH: have a Tulasi psychiatrist review every entry, then set
// `REVIEWED_BY` / `REVIEWED_ON` below (shown on each page). Update this file,
// not the client, when anything changes.
//
// House rules for every entry:
//   - No doses, ever. Dosing is individual and belongs to the prescriber.
//   - Plain language, and "may"/"can": not everyone gets every effect.
//   - `serious` lists the signs that need medical help right away.
//   - Never suggest starting, stopping, or changing a medicine.

export const REVIEWED_BY = null; // e.g. "Dr. Gorav Gupta, Senior Consultant Psychiatrist"
export const REVIEWED_ON = null; // e.g. "2026-10-20"

export const MEDICINE_CATEGORIES = [
  { id: "antidepressant", label: "Antidepressants", icon: "🌤️" },
  { id: "antipsychotic", label: "Antipsychotics", icon: "🧩" },
  { id: "mood_stabiliser", label: "Mood stabilisers", icon: "⚖️" },
  { id: "anxiety_sleep", label: "Anxiety & calming", icon: "🍃" },
  { id: "adhd", label: "ADHD", icon: "🎯" },
  { id: "deaddiction", label: "De-addiction", icon: "🌱" },
];

// ---- shared wording -------------------------------------------------------

const ALLERGY = "Swelling of the face, lips or tongue, trouble breathing, or a widespread rash (allergic reaction)";
const SUICIDAL = "New or worse thoughts of suicide or self-harm, especially in the first weeks, after a dose change, or in people under 25";
const MANIA = "Unusually high energy, little need for sleep, racing thoughts or reckless behaviour (possible mania)";
const SEROTONIN =
  "Agitation, high fever, sweating, fast heartbeat, muscle twitching or stiffness, or confusion (possible serotonin syndrome, especially when combined with other medicines)";
const NMS = "High fever with very stiff muscles, confusion and sweating (a rare but serious reaction)";
const TD = "Movements you can't control, especially of the face, lips or tongue";
const HIGH_SUGAR = "Feeling very thirsty, passing urine often, or feeling very tired (possible high blood sugar)";
const LIVER = "Yellowing of the skin or eyes, dark urine, or pain in the upper right of the stomach (possible liver problem)";
const DONT_STOP_ANTIDEPRESSANT =
  "Don't stop suddenly, even when you feel better. That can cause dizziness, 'electric-shock' feelings, irritability or flu-like symptoms. Your doctor will reduce it gradually when the time is right.";
const ALCOHOL = "Avoid alcohol: it can worsen side effects and work against the medicine.";
const PREGNANCY = "If you're pregnant, planning a pregnancy or breastfeeding, talk to your doctor. Don't stop the medicine on your own.";
const OTHER_MEDS = "Tell every doctor and pharmacist what you take, including painkillers, herbal remedies and supplements.";

const SSRI_COMMON = [
  "Nausea or an upset stomach",
  "Headache",
  "Trouble sleeping, or feeling sleepy",
  "Sweating",
  "Dry mouth",
  "Sexual side effects (lower desire, delayed orgasm)",
];
const SSRI_COMMON_NOTE = "Many early side effects ease within 1–2 weeks.";
const SSRI_SERIOUS = [SUICIDAL, SEROTONIN, MANIA, "Unusual bleeding or bruising", ALLERGY];
const SSRI_GOOD_TO_KNOW = [
  DONT_STOP_ANTIDEPRESSANT,
  ALCOHOL,
  "Painkillers like aspirin or ibuprofen can raise the risk of bleeding. Check with your doctor before taking them regularly.",
  PREGNANCY,
  OTHER_MEDS,
];
const ANTIDEPRESSANT_TIME = "Sleep and energy can improve within 1–2 weeks. Mood usually lifts over 4–6 weeks, so it's worth giving it time.";

const ANTIPSYCHOTIC_SERIOUS = [NMS, TD, HIGH_SUGAR, "Fainting or a very fast or irregular heartbeat", ALLERGY];
const ANTIPSYCHOTIC_GOOD_TO_KNOW = [
  "Don't stop suddenly. Symptoms can come back, sometimes quickly. Any change should be planned with your doctor.",
  "Regular checks of weight, blood sugar and cholesterol are part of safe treatment.",
  ALCOHOL,
  "It can make you drowsy. Take care driving or using machines until you know how it affects you.",
  PREGNANCY,
];
const ANTIPSYCHOTIC_TIME = "Agitation and sleep often improve within days. Hallucinations and other symptoms usually ease over a few weeks.";

const BENZO_SERIOUS = [
  "Very slow or shallow breathing, or being very hard to wake, especially if taken with alcohol, opioid painkillers or other sedatives",
  "Severe confusion, or falls",
  SUICIDAL,
  ALLERGY,
];
const BENZO_GOOD_TO_KNOW = [
  "It can be habit-forming, so it's usually prescribed for a short time.",
  "After regular use, never stop suddenly: withdrawal can cause severe anxiety and, rarely, seizures. Your doctor will taper it.",
  "Never mix it with alcohol.",
  "Don't drive or use machines until you know how it affects you.",
  "Keep it somewhere safe, away from others.",
];

// ---- the guide ------------------------------------------------------------

export const MEDICINES = [
  // Antidepressants
  {
    slug: "sertraline",
    name: "Sertraline",
    kind: "SSRI antidepressant",
    category: "antidepressant",
    usedFor: ["Depression", "Anxiety disorders", "OCD", "Panic disorder", "PTSD"],
    howItHelps: [
      "Gradually lifts low mood and brings back interest in things",
      "Reduces constant worry and panic attacks",
      "Helps loosen the grip of obsessive thoughts and compulsions",
    ],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: SSRI_COMMON,
    commonNote: SSRI_COMMON_NOTE,
    serious: SSRI_SERIOUS,
    goodToKnow: SSRI_GOOD_TO_KNOW,
  },
  {
    slug: "escitalopram",
    name: "Escitalopram",
    kind: "SSRI antidepressant",
    category: "antidepressant",
    usedFor: ["Depression", "Generalised anxiety", "Panic disorder", "Social anxiety", "OCD"],
    howItHelps: ["Gradually lifts low mood", "Reduces constant worry, tension and panic", "Can make social situations feel less overwhelming"],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: SSRI_COMMON,
    commonNote: SSRI_COMMON_NOTE,
    serious: [...SSRI_SERIOUS, "Fainting or a pounding, irregular heartbeat"],
    goodToKnow: [...SSRI_GOOD_TO_KNOW, "Tell your doctor about any heart rhythm problems, as it can affect heart rhythm in some people."],
  },
  {
    slug: "fluoxetine",
    name: "Fluoxetine",
    kind: "SSRI antidepressant",
    category: "antidepressant",
    usedFor: ["Depression", "OCD", "Panic disorder", "Bulimia"],
    howItHelps: ["Gradually lifts low mood and energy", "Reduces obsessive thoughts and compulsions", "Can reduce binge-eating and purging urges"],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: [...SSRI_COMMON, "Feeling restless or 'wired' (it's often taken in the morning)"],
    commonNote: SSRI_COMMON_NOTE,
    serious: SSRI_SERIOUS,
    goodToKnow: [
      "It stays in the body for a long time, so missed doses matter less and stopping effects are usually milder. Still, only stop with your doctor's plan.",
      ...SSRI_GOOD_TO_KNOW.slice(1),
    ],
  },
  {
    slug: "paroxetine",
    name: "Paroxetine",
    kind: "SSRI antidepressant",
    category: "antidepressant",
    usedFor: ["Depression", "Panic disorder", "Social anxiety", "Generalised anxiety", "OCD", "PTSD"],
    howItHelps: ["Gradually lifts low mood", "Reduces anxiety, panic and social fear", "Helps with obsessive thoughts"],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: [...SSRI_COMMON, "Weight gain"],
    commonNote: SSRI_COMMON_NOTE,
    serious: SSRI_SERIOUS,
    goodToKnow: [
      "Stopping effects can be stronger than with similar medicines, so it's important not to miss doses or stop suddenly.",
      "It's usually avoided in pregnancy. If you're pregnant or planning to be, talk to your doctor before making any change.",
      ALCOHOL,
      OTHER_MEDS,
    ],
  },
  {
    slug: "venlafaxine",
    name: "Venlafaxine",
    kind: "SNRI antidepressant",
    category: "antidepressant",
    usedFor: ["Depression", "Generalised anxiety", "Social anxiety", "Panic disorder"],
    howItHelps: ["Lifts low mood and energy", "Reduces worry and physical tension"],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: ["Nausea", "Sweating", "Dizziness", "Headache", "Dry mouth", "Sexual side effects", "Raised blood pressure"],
    commonNote: SSRI_COMMON_NOTE,
    serious: [...SSRI_SERIOUS, "Severe headache, chest pain or a pounding heartbeat (possible high blood pressure)"],
    goodToKnow: [
      "Stopping effects can be strong, even after a missed dose, so take it regularly and never stop suddenly.",
      "Your doctor may check your blood pressure from time to time.",
      ALCOHOL,
      PREGNANCY,
      OTHER_MEDS,
    ],
  },
  {
    slug: "duloxetine",
    name: "Duloxetine",
    kind: "SNRI antidepressant",
    category: "antidepressant",
    usedFor: ["Depression", "Generalised anxiety", "Nerve pain (e.g. diabetic)", "Fibromyalgia"],
    howItHelps: ["Lifts low mood", "Reduces worry", "Can ease long-term nerve and body pain"],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: ["Nausea", "Dry mouth", "Constipation", "Tiredness", "Sweating", "Less appetite", "Sexual side effects"],
    commonNote: SSRI_COMMON_NOTE,
    serious: [...SSRI_SERIOUS, LIVER],
    goodToKnow: [DONT_STOP_ANTIDEPRESSANT, "Avoid heavy drinking, which raises the risk of liver problems.", PREGNANCY, OTHER_MEDS],
  },
  {
    slug: "mirtazapine",
    name: "Mirtazapine",
    kind: "Antidepressant (NaSSA)",
    category: "antidepressant",
    usedFor: ["Depression, especially with poor sleep or appetite"],
    howItHelps: ["Lifts low mood", "Often improves sleep early on", "Can bring back a poor appetite"],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: ["Sleepiness (it's usually taken at night)", "Increased appetite and weight gain", "Dry mouth", "Dizziness"],
    commonNote: "Sexual side effects are less common than with many antidepressants.",
    serious: [SUICIDAL, MANIA, "Sore throat, fever or mouth ulcers that won't go away (rarely, a drop in white blood cells; you may need a blood test)", ALLERGY],
    goodToKnow: [DONT_STOP_ANTIDEPRESSANT, "Alcohol adds to the drowsiness, so avoid it.", PREGNANCY, OTHER_MEDS],
  },
  {
    slug: "bupropion",
    name: "Bupropion",
    kind: "Antidepressant (NDRI)",
    category: "antidepressant",
    usedFor: ["Depression", "Help to stop smoking"],
    howItHelps: ["Lifts low mood and energy", "Reduces cravings when stopping smoking"],
    timeToWork: ANTIDEPRESSANT_TIME,
    common: ["Dry mouth", "Trouble sleeping", "Headache", "Nausea", "Feeling jittery"],
    commonNote: "It's less likely than many antidepressants to cause weight gain or sexual side effects.",
    serious: ["A seizure (fit)", SUICIDAL, MANIA, "Severe headache or pounding heartbeat (possible high blood pressure)", ALLERGY],
    goodToKnow: [
      "Tell your doctor about any history of seizures, eating disorders or head injury, which raise the seizure risk.",
      "Avoid heavy drinking, and don't stop alcohol or sleeping tablets suddenly while taking it: both raise the seizure risk.",
      PREGNANCY,
      OTHER_MEDS,
    ],
  },
  {
    slug: "amitriptyline",
    name: "Amitriptyline",
    kind: "Tricyclic antidepressant",
    category: "antidepressant",
    usedFor: ["Nerve pain", "Migraine prevention", "Depression", "Sleep problems (at low doses)"],
    howItHelps: ["Eases long-term nerve pain", "Helps prevent migraines", "Improves sleep", "Lifts mood at higher doses"],
    timeToWork: "Sleep can improve within days. Pain relief and mood benefits build over 2–6 weeks.",
    common: ["Drowsiness", "Dry mouth", "Constipation", "Blurred vision", "Weight gain", "Dizziness when standing up"],
    commonNote: "Standing up slowly helps with dizziness.",
    serious: ["A fast or irregular heartbeat, or fainting", "Trouble passing urine", "Severe confusion", SUICIDAL, ALLERGY],
    goodToKnow: [
      "Taking too much is very dangerous. Keep it safely stored, and if you're having thoughts of harming yourself, tell someone and get help right away.",
      "Alcohol adds to the drowsiness, so avoid it.",
      "Tell your doctor about any heart problems or glaucoma.",
      DONT_STOP_ANTIDEPRESSANT,
    ],
  },

  // Antipsychotics
  {
    slug: "olanzapine",
    name: "Olanzapine",
    kind: "Antipsychotic",
    category: "antipsychotic",
    usedFor: ["Schizophrenia", "Bipolar disorder (mania, and preventing relapse)"],
    howItHelps: ["Reduces hallucinations and suspicious or confused thoughts", "Calms mania and agitation", "Improves sleep"],
    timeToWork: ANTIPSYCHOTIC_TIME,
    common: ["Drowsiness", "Increased appetite and weight gain", "Dizziness", "Dry mouth", "Constipation"],
    commonNote: "Weight gain is common, so healthy eating and activity from the start really help.",
    serious: ANTIPSYCHOTIC_SERIOUS,
    goodToKnow: ANTIPSYCHOTIC_GOOD_TO_KNOW,
  },
  {
    slug: "risperidone",
    name: "Risperidone",
    kind: "Antipsychotic",
    category: "antipsychotic",
    usedFor: ["Schizophrenia", "Bipolar mania", "Irritability and aggression in autism", "Severe behaviour problems"],
    howItHelps: ["Reduces hallucinations and disturbed thinking", "Calms mania, aggression and irritability"],
    timeToWork: ANTIPSYCHOTIC_TIME,
    common: [
      "Drowsiness",
      "Weight gain",
      "Restlessness, stiffness or tremor",
      "Hormone effects: missed periods, breast swelling or discharge, sexual problems",
    ],
    commonNote: "Tell your doctor about hormone-related changes. There are often ways to help.",
    serious: ANTIPSYCHOTIC_SERIOUS,
    goodToKnow: ANTIPSYCHOTIC_GOOD_TO_KNOW,
  },
  {
    slug: "quetiapine",
    name: "Quetiapine",
    kind: "Antipsychotic",
    category: "antipsychotic",
    usedFor: ["Schizophrenia", "Bipolar disorder (mania and depression)", "Add-on treatment for depression"],
    howItHelps: ["Reduces hallucinations and disturbed thinking", "Calms mania", "Can lift bipolar depression", "Improves sleep"],
    timeToWork: ANTIPSYCHOTIC_TIME,
    common: ["Sleepiness", "Dizziness when standing up", "Dry mouth", "Constipation", "Weight gain"],
    commonNote: "Standing up slowly helps with dizziness.",
    serious: ANTIPSYCHOTIC_SERIOUS,
    goodToKnow: ["It isn't a sleeping pill, and shouldn't be used just for sleep unless your doctor has advised it.", ...ANTIPSYCHOTIC_GOOD_TO_KNOW],
  },
  {
    slug: "aripiprazole",
    name: "Aripiprazole",
    kind: "Antipsychotic",
    category: "antipsychotic",
    usedFor: ["Schizophrenia", "Bipolar disorder", "Add-on treatment for depression", "Irritability in autism", "Tic disorders"],
    howItHelps: ["Reduces hallucinations and disturbed thinking", "Calms mania", "Can boost an antidepressant's effect"],
    timeToWork: ANTIPSYCHOTIC_TIME,
    common: ["An inner restlessness or urge to keep moving", "Nausea", "Headache", "Trouble sleeping", "Dizziness"],
    commonNote: "It's less likely than many antipsychotics to cause weight gain or drowsiness. Tell your doctor about restlessness, as it can usually be helped.",
    serious: [
      ...ANTIPSYCHOTIC_SERIOUS,
      "New, hard-to-control urges, such as gambling, shopping, binge eating or sexual urges. Tell your doctor even if it feels embarrassing.",
    ],
    goodToKnow: ANTIPSYCHOTIC_GOOD_TO_KNOW,
  },

  // Mood stabilisers
  {
    slug: "lithium",
    name: "Lithium",
    kind: "Mood stabiliser",
    category: "mood_stabiliser",
    usedFor: ["Bipolar disorder (treating and preventing mania and depression)", "Add-on treatment for depression"],
    howItHelps: ["Evens out extreme highs and lows", "Helps prevent future episodes", "Reduces the risk of suicide over the long term"],
    timeToWork: "Mania usually settles over 1–3 weeks. Its protective effect builds over months of steady use.",
    common: ["Thirst and passing more urine", "A mild hand tremor", "Nausea", "Weight gain", "A metallic taste"],
    commonNote: "Mild side effects often settle as your body adjusts.",
    serious: [
      "Vomiting or diarrhoea, a coarse tremor, unsteadiness, slurred speech, confusion or unusual drowsiness (possible lithium toxicity). Get medical help right away.",
      ALLERGY,
    ],
    goodToKnow: [
      "Regular blood tests check the lithium level, kidneys and thyroid. They're essential for using it safely.",
      "Keep your salt and fluid intake steady. Drink more in hot weather or when sweating a lot.",
      "Vomiting, diarrhoea or fever can push the level up. Contact your doctor if you're unwell.",
      "Some common painkillers (like ibuprofen) and some blood-pressure medicines can raise lithium levels. Always check first.",
      PREGNANCY,
    ],
  },
  {
    slug: "valproate",
    name: "Sodium valproate / Divalproex",
    kind: "Mood stabiliser and anti-seizure medicine",
    category: "mood_stabiliser",
    usedFor: ["Bipolar disorder (mania, and preventing relapse)", "Epilepsy", "Migraine prevention"],
    howItHelps: ["Calms mania", "Helps prevent future mood episodes", "Prevents seizures"],
    timeToWork: "Mania often eases within 1–2 weeks.",
    common: ["Nausea or stomach upset", "Weight gain", "Tremor", "Hair thinning", "Drowsiness"],
    commonNote: "Some side effects ease over time. Tell your doctor if they bother you.",
    serious: [LIVER, "Severe stomach pain with vomiting (possible pancreas problem)", "Unusual bruising or bleeding", "Confusion or unusual drowsiness", ALLERGY],
    goodToKnow: [
      "It carries a high risk of birth defects and developmental problems. Anyone who could become pregnant needs a careful discussion with their doctor and reliable contraception. Never stop it on your own.",
      "Regular blood tests check the level, liver and blood count.",
      ALCOHOL,
      OTHER_MEDS,
    ],
  },
  {
    slug: "lamotrigine",
    name: "Lamotrigine",
    kind: "Mood stabiliser and anti-seizure medicine",
    category: "mood_stabiliser",
    usedFor: ["Bipolar disorder (preventing depressive episodes)", "Epilepsy"],
    howItHelps: ["Helps prevent bipolar depression from returning", "Prevents seizures"],
    timeToWork: "The dose is raised slowly over several weeks, so benefits build gradually.",
    common: ["Headache", "Dizziness", "Double or blurred vision", "Nausea", "Trouble sleeping"],
    commonNote: "Raising the dose slowly keeps side effects down.",
    serious: [
      "ANY new rash, especially with fever, blisters, mouth sores or sore eyes. Rare but serious skin reactions are most likely in the first 8 weeks. Get medical help right away.",
      SUICIDAL,
      ALLERGY,
    ],
    goodToKnow: [
      "The dose must go up slowly, exactly as prescribed.",
      "If you miss several days, don't restart at your usual dose. Ask your doctor how to restart.",
      "Valproate and some hormonal contraceptives change its levels. Tell your doctor about all medicines.",
      PREGNANCY,
    ],
  },

  // Anxiety & calming
  {
    slug: "clonazepam",
    name: "Clonazepam",
    kind: "Benzodiazepine",
    category: "anxiety_sleep",
    usedFor: ["Panic disorder", "Short-term relief of severe anxiety", "Some seizure disorders"],
    howItHelps: ["Calms anxiety and panic quickly", "Can help in the early weeks while other treatment starts working"],
    timeToWork: "Usually within an hour.",
    common: ["Drowsiness", "Unsteadiness", "Slowed thinking or poor memory", "Tiredness"],
    commonNote: "These are often worse at the start and with higher doses.",
    serious: BENZO_SERIOUS,
    goodToKnow: BENZO_GOOD_TO_KNOW,
  },
  {
    slug: "alprazolam",
    name: "Alprazolam",
    kind: "Benzodiazepine",
    category: "anxiety_sleep",
    usedFor: ["Panic disorder", "Short-term relief of severe anxiety"],
    howItHelps: ["Calms anxiety and panic quickly"],
    timeToWork: "Within an hour, but it wears off fairly quickly.",
    common: ["Drowsiness", "Unsteadiness", "Slowed thinking or poor memory", "Anxiety coming back between doses"],
    commonNote: "Because it's short-acting, some people feel anxiety return as each dose wears off.",
    serious: BENZO_SERIOUS,
    goodToKnow: ["It carries a higher risk of dependence than longer-acting medicines of the same kind.", ...BENZO_GOOD_TO_KNOW],
  },
  {
    slug: "propranolol",
    name: "Propranolol",
    kind: "Beta-blocker",
    category: "anxiety_sleep",
    usedFor: ["Physical anxiety symptoms (pounding heart, shaking)", "Performance anxiety", "Migraine prevention", "High blood pressure"],
    howItHelps: ["Calms a racing heart, trembling and sweating", "Doesn't cause drowsiness or dependence the way calming tablets can"],
    timeToWork: "Within an hour or two when taken for anxiety symptoms.",
    common: ["Tiredness", "Cold hands and feet", "Sleep problems or vivid dreams", "Dizziness"],
    commonNote: "It treats the body's anxiety symptoms, not worrying thoughts.",
    serious: ["Wheezing or breathlessness", "A very slow heartbeat, fainting or severe dizziness", ALLERGY],
    goodToKnow: [
      "It's not suitable for people with asthma. Tell your doctor if you have asthma, heart problems or diabetes.",
      "In diabetes it can hide the warning signs of low blood sugar.",
      "If taken regularly, don't stop suddenly, as that can strain the heart.",
    ],
  },

  // ADHD
  {
    slug: "methylphenidate",
    name: "Methylphenidate",
    kind: "Stimulant (ADHD medicine)",
    category: "adhd",
    usedFor: ["ADHD in children and adults"],
    howItHelps: ["Improves focus and attention", "Reduces restlessness and impulsive behaviour"],
    timeToWork: "It works the same day, usually within an hour.",
    common: ["Less appetite", "Trouble sleeping", "Headache", "Stomach ache", "Irritability as it wears off"],
    commonNote: "Taking it in the morning, after breakfast, often helps appetite and sleep.",
    serious: [
      "Chest pain, fainting, or a very fast heartbeat",
      "Seeing or hearing things that aren't there, or severe mood changes",
      SUICIDAL,
      ALLERGY,
    ],
    goodToKnow: [
      "Height, weight, heart rate and blood pressure are checked regularly, especially in children.",
      "It's a controlled medicine. Keep it safe, and never share it.",
      "Tell your doctor about any heart problems or tics, or family history of heart problems.",
    ],
  },
  {
    slug: "atomoxetine",
    name: "Atomoxetine",
    kind: "Non-stimulant ADHD medicine",
    category: "adhd",
    usedFor: ["ADHD in children and adults"],
    howItHelps: ["Improves focus and attention", "Reduces impulsivity", "Works through the whole day"],
    timeToWork: "Builds up gradually: some change in 1–2 weeks, full effect over 6–12 weeks.",
    common: ["Less appetite", "Nausea or stomach ache", "Tiredness", "Mood swings"],
    commonNote: "Taking it with food can help with stomach upset.",
    serious: [SUICIDAL, LIVER, "A very fast heartbeat or fainting", ALLERGY],
    goodToKnow: ["It isn't a controlled medicine and isn't habit-forming.", "Height, weight and blood pressure are checked regularly in children."],
  },

  // De-addiction
  {
    slug: "chlordiazepoxide",
    name: "Chlordiazepoxide",
    kind: "Benzodiazepine (for alcohol withdrawal)",
    category: "deaddiction",
    usedFor: ["Safely managing alcohol withdrawal (detox)"],
    howItHelps: ["Eases shaking, sweating, anxiety and sleeplessness during withdrawal", "Lowers the risk of withdrawal seizures"],
    timeToWork: "Within hours. It's usually given for about a week, with the dose reduced each day.",
    common: ["Drowsiness", "Unsteadiness", "Tiredness"],
    commonNote: "It's meant for a short course under medical supervision.",
    serious: [...BENZO_SERIOUS, "Seeing or hearing things, severe confusion or shaking during withdrawal (needs urgent medical care)"],
    goodToKnow: [
      "Stopping alcohol suddenly after heavy daily drinking can be dangerous. Detox should be medically supervised.",
      "Never drink alcohol while taking it: the combination can be life-threatening.",
      "Take it only for as long as prescribed. It's habit-forming if used long-term.",
    ],
  },
  {
    slug: "disulfiram",
    name: "Disulfiram",
    kind: "Alcohol deterrent",
    category: "deaddiction",
    usedFor: ["Staying off alcohol after stopping"],
    howItHelps: ["Makes drinking very unpleasant, which helps people stick to a decision not to drink"],
    timeToWork: "Works from the first doses, as long as it's taken daily.",
    common: ["Drowsiness", "A metallic or garlic-like taste", "Headache"],
    commonNote: "If alcohol is taken, it causes flushing, a pounding headache, vomiting, a fast heartbeat and breathlessness. That reaction can be dangerous.",
    serious: [
      "A reaction after drinking that includes chest pain, severe breathlessness or fainting",
      LIVER,
      "Confusion, or eye pain or changes in vision",
      ALLERGY,
    ],
    goodToKnow: [
      "It must only ever be taken with the person's full knowledge and agreement. Giving it secretly is dangerous and can be life-threatening.",
      "No alcohol for at least 12 hours before starting, and for up to 2 weeks after stopping.",
      "Watch for hidden alcohol in cough syrups, mouthwashes, some sauces and vinegars, aftershaves and hand sanitisers.",
      "It works best alongside counselling and support.",
    ],
  },
  {
    slug: "naltrexone",
    name: "Naltrexone",
    kind: "Craving reducer",
    category: "deaddiction",
    usedFor: ["Alcohol dependence", "Opioid dependence (after detox)"],
    howItHelps: ["Reduces cravings", "Makes drinking feel less rewarding, so a slip is less likely to turn into a relapse"],
    timeToWork: "Some people notice fewer cravings within the first week or two.",
    common: ["Nausea", "Headache", "Dizziness", "Tiredness", "Trouble sleeping"],
    commonNote: "Nausea is usually mild and settles.",
    serious: [LIVER, "Sudden severe withdrawal symptoms if any opioids are still in the body", ALLERGY],
    goodToKnow: [
      "You must be completely off opioids (including some painkillers and cough medicines) for 7–10 days before starting, or it can trigger sudden withdrawal.",
      "Opioid painkillers won't work while you're taking it. Carry a card or tell any doctor treating you.",
      "After stopping it, the body's tolerance to opioids is lower, so a previous amount can cause a fatal overdose.",
      "It works best alongside counselling and support.",
    ],
  },
  {
    slug: "acamprosate",
    name: "Acamprosate",
    kind: "Craving reducer",
    category: "deaddiction",
    usedFor: ["Staying off alcohol after detox"],
    howItHelps: ["Reduces cravings and the restless, uneasy feelings after stopping drinking"],
    timeToWork: "It's started after detox and taken regularly. Its benefit builds over weeks.",
    common: ["Diarrhoea", "Nausea", "Itching", "Low mood"],
    commonNote: "Diarrhoea is the most common side effect and often settles.",
    serious: [SUICIDAL, "Severe or ongoing diarrhoea", ALLERGY],
    goodToKnow: [
      "Keep taking it even if you have a slip. Tell your doctor, but don't stop on your own.",
      "Tell your doctor about kidney problems, as the dose may need adjusting.",
      "It works best alongside counselling and support.",
    ],
  },
];

const BY_SLUG = new Map(MEDICINES.map((m) => [m.slug, m]));

export function getMedicine(slug) {
  return BY_SLUG.get(String(slug || "").toLowerCase()) || null;
}

// Other names people type: alternative generic names and common spellings.
// (Brand names are left out on purpose: there are hundreds in India and a
// wrong one would point someone at the wrong medicine.)
const ALIASES = {
  valproate: ["valproate", "valproic", "divalproex", "sodium valproate"],
  escitalopram: ["escitalopram", "escitalopam"],
  sertraline: ["sertraline", "sertaline"],
  quetiapine: ["quetiapine", "quetiapin"],
};

const NAME_PATTERNS = MEDICINES.map((m) => {
  const names = ALIASES[m.slug] || [m.slug];
  return { medicine: m, pattern: new RegExp(`\\b(?:${names.join("|")})\\b`, "i") };
});

/** The guide's medicines named in a message (at most three). */
export function findMedicinesIn(text) {
  if (!text) return [];
  return NAME_PATTERNS.filter((p) => p.pattern.test(text))
    .map((p) => p.medicine)
    .slice(0, 3);
}

/** The list view: enough for a card, without the full detail. */
export function medicineSummary(m) {
  return { slug: m.slug, name: m.name, kind: m.kind, category: m.category, usedFor: m.usedFor };
}
